Lab1
LacqueredNoCap/clojure-labs-nsu pull request #1
Opened 2022-10-12 00:33 UTC by LacqueredNoCap

2022-11-01 12:01 UTC, shishkin-pavel requested changes

2022-11-01 12:01 UTC, shishkin-pavel commented on src/main/clojure/lab1/lab12.clj
> +  ((fn [elementsLoop combinationsLoop]
`loop`

2022-11-01 12:01 UTC, shishkin-pavel commented on src/main/clojure/lab1/lab13.clj
> +    (reverse (reduce func nil coll))
давай свой редьюс напишем?
и давай сделаем без ревёрсов, но зато с конкатом (и объясним почему сложность полученных мапа и фильтра -- O(n))

2022-11-01 12:01 UTC, shishkin-pavel commented on src/main/clojure/lab1/lab14.clj
> +    (letfn [(addMap [filteredElements] (cons filteredElements combination))]
`letfn`/`let` позволяют задавать по несколько биндингов за раз

2022-11-02 01:13 UTC, LacqueredNoCap commented on src/main/clojure/lab1/lab14.clj
> +    (letfn [(addMap [filteredElements] (cons filteredElements combination))]
+

2022-11-02 01:55 UTC, LacqueredNoCap commented on src/main/clojure/lab1/lab13.clj
> +    (reverse (reduce func nil coll))
\+ my-reduce
my-reduce работает за O(n) (n - размер списка), а добавление элемента к lazy sequence (concat) - O(1). Получается, my-map и my-filter работают за O(n)

2022-11-03 14:47 UTC, LacqueredNoCap commented on src/main/clojure/lab1/lab12.clj
> +  ((fn [elementsLoop combinationsLoop]
\+

2022-11-07 10:46 UTC, shishkin-pavel approved these changes

2022-11-08 01:35 UTC, merged