Lab2
LacqueredNoCap/clojure-labs-nsu pull request #2
Opened 2022-10-28 01:23 UTC by LacqueredNoCap

Новохацкий Аркадий 22221

2022-11-03 12:04 UTC, shishkin-pavel commented
а давай дальше от мастера ответвляться? чтобы не было лишних файликов в ревью

2022-11-09 13:24 UTC, shishkin-pavel requested changes

2022-11-09 13:24 UTC, shishkin-pavel commented on src/main/clojure/lab2/lab21.clj
> +(def step 1)
глобальные константы -- не ок
мы же библиотеку для решения какой-то задачи пишем, зачем её пользователям предзаданный степ?

2022-11-09 13:24 UTC, shishkin-pavel commented on src/main/clojure/lab2/lab21.clj
> +(def memoizeFxn (memoize fxn))
две проблемы:
мемоизация самих частичных сумм приводит к тому, что вместо дешёвой арифметики (на регистрах) нам придётся обходить какие-то значения в памяти и складывать их
память достаточно дорогая, поэтому это не ок решение, мемоизировать надо значение интеграла для диапазона [0, n], тогда при вычислении интеграла [0, n+1] мы сможем взять мемоизированное значение для меньшего интеграла (всего одно, а не все n частичных сумм) и прибавить к нему ещё одну трапецию

вторая проблема: хранение мемоизации в глобале (def)
мемоизация -- кэш, но управлять (например, дропнуть какие-то значения) мы им не можем
если мы положили кэш в глобал, он будет только накапливать значения даже если они нам уже никогда не нужны
поэтому мемоизации должны храниться в каких-то локальных объектах, которые гц когда-то соберёт

2022-11-09 13:24 UTC, shishkin-pavel commented on src/main/clojure/lab2/lab22.clj
> +(prn (time ((integrate line) 10))) ; = 110
а почему между этим вызовом и следующим нет прироста производительности?
пусть будет не 10 и 12, а 100000 и 100001, последовательность должна же быть одна? значит для второго вызова мы только одну трапецию должны добавить?
(надо что-то починить)

2022-11-13 10:07 UTC, LacqueredNoCap commented on src/main/clojure/lab2/lab21.clj
> +(def step 1)
\+

2022-11-13 10:07 UTC, LacqueredNoCap commented on src/main/clojure/lab2/lab21.clj
> +(def memoizeFxn (memoize fxn))
\+

2022-11-13 10:07 UTC, LacqueredNoCap commented on src/main/clojure/lab2/lab22.clj
> +(prn (time ((integrate line) 10))) ; = 110
\+

2022-11-21 11:10 UTC, shishkin-pavel requested changes
2.2 замечание

2022-11-21 11:10 UTC, shishkin-pavel commented on src/main/clojure/lab2/lab22.clj
> +(prn (time ((integrate line) 10))) ; = 110
но тут ничего не изменилось?

2022-11-21 11:10 UTC, shishkin-pavel commented on src/main/clojure/lab2/lab21.clj
> +(def nonMemInt (integrate line 1))
лучше всё-таки let, как при обычном использовании (а то сейчас у нас опять мемоизация в глобале)

2022-11-23 02:32 UTC, LacqueredNoCap commented on src/main/clojure/lab2/lab21.clj
> +(def nonMemInt (integrate line 1))
\+

2022-11-23 02:49 UTC, LacqueredNoCap commented on src/main/clojure/lab2/lab22.clj
> +(prn (time ((integrate line) 10))) ; = 110
\+

2022-11-27 23:05 UTC, shishkin-pavel approved these changes

2022-11-28 02:06 UTC, merged