Lab 3
LacqueredNoCap/clojure-labs-nsu pull request #3
Opened 2022-11-04 05:45 UTC by LacqueredNoCap

Новохацкий Аркадий 22221

2022-11-28 20:59 UTC, shishkin-pavel requested changes

2022-11-28 20:59 UTC, shishkin-pavel commented on src/main/clojure/lab3/lab32.clj
> +(defn splitCollection [n coll]
всё хорошо, но есть нюанс: при передаче конечной последовательности обычный фильтр вернёт конечный результат, а твой фильтр -- нет

2022-11-28 21:03 UTC, shishkin-pavel requested changes

2022-11-28 21:03 UTC, shishkin-pavel commented on src/main/clojure/lab3/lab31.clj
> +       (flatten)
о, и ещё флаттен -- представим, что мы фильтруем не примитивы, а коллекции -- флаттен их расплющит
поэтому надо использовать mapcat

2022-12-02 11:55 UTC, LacqueredNoCap commented on src/main/clojure/lab3/lab31.clj
> +       (flatten)
\+

2022-12-02 13:50 UTC, LacqueredNoCap commented on src/main/clojure/lab3/lab32.clj
> +(defn splitCollection [n coll]
\+

2022-12-04 14:19 UTC, shishkin-pavel approved these changes

2022-12-04 14:19 UTC, shishkin-pavel commented on src/main/clojure/lab3/lab31.clj
> +       (mapcat #(concat %))
на мой взгляд, было бы несколько понятнее написать 
```
(mapcat deref)
(mapcat identity)
```
, но и так норм

2022-12-04 17:04 UTC, merged